site_name: YoungZM's CS Learning Log
site_url: https://csdiy.wiki/
site_author: YoungZM339
site_description: >-
    YoungZM's CS Learning Log

repo_name: cs-learning-log
repo_url: https://github.com/youngzm339/cs-learning-log/

copyright: Copyright &copy; 2021-present <a href="https://github.com/YoungZM339" target="_blank" rel="noopener noreferrer">YoungZM</a>

theme:
    name: material
    language: zh

    static_templates:
        - 404.html

    include_search_page: false
    search_index_only: true

    features:
        - header.autohide
        # - navigation.instant
        # - navigation.expand
        # - navigation.sections
        - navigation.tracking
        # - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        # - navigation.indexes
        - search.highlight
        - search.share
        - search.suggest
        # - toc.integrate
        - content.code.annotate

    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: light blue
          accent: deep purple
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: cyan
          accent: deep purple
          toggle:
              icon: material/weather-night
              name: Switch to light mode

    font:
        text: Roboto
        code: Roboto Mono
    icon:
        repo: fontawesome/brands/github

    custom_dir: overrides

plugins:
    - search:
          lang: ja
    - git-revision-date-localized
    - minify:
          minify_html: true

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/YoungZM339/cs-learning-log/
    analytics:
        provider: google
        property: UA-170465513-1

nav:
    - 前言: "index.md"
    - 计算机网络:
        - "USTC Computer Networking:A Top-Down Approach": "ComputerNetwork\topdown_ustc.md"
